obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.25, 0.29], [0.07, 0.29], [0.07, -0.29], [-0.25, -0.29]]
inflation_radius: 0.55

observation_sources: scan

scan: {sensor_frame: camera_depth_frame, data_type: LaserScan, topic: scan, marking: true, clearing: true}
