obstacle_range: 2.5
raytrace_range: 3.0
#footprint: [[-0.2, -0.25], [-0.2, 0.15], [0.2, 0.15], [0.2, -0.25]]
footprint: [[-0.26, -0.24], [0.15, -0.24], [0.15, 0.24], [-0.26, 0.24]]
#robot_radius: ir_of_robot
inflation_radius: 0.55

observation_sources: scan

scan: {sensor_frame: camera_depth_frame, data_type: LaserScan, topic: scan, marking: true, clearing: true}
